# frozen_string_literal: true

opt_out_usage
default_platform(:android)

platform :android do
  desc 'Validate key'
  lane :validate_key do
    validate_play_store_json_key
  end

  desc 'Verify the build'
  lane :build_release do
    build_release
  end

  desc 'Runs all the tests'
  lane :test do
    gradle(task: 'test')
  end

  desc 'Submit a new Beta Build to Google Play'
  lane :beta do
    build_release
    upload_to_play_store(track: 'internal')
    slack(message: "Android beta app successfully deployed to Play Store!")
  end

  desc 'Deploy a new version to the Google Play'
  lane :production do
    build_release
    upload_to_play_store
    slack(message: "Android app successfully released to Play Store!")
  end
end

def build_release
  gradle(task: 'clean bundleRelease')
end

def bump_version
  Dir.chdir("..") do
    sh("bumpver", "update")
  end
end
